// <auto-generated />
using System;
using CNPM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CNPM.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20260629012834_AddModelsGioiThieu")]
    partial class AddModelsGioiThieu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CNPM.Models.BangDiem", b =>
                {
                    b.Property<int>("MaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiem"));

                    b.Property<double?>("Diem15P")
                        .HasColumnType("float");

                    b.Property<double?>("Diem45P")
                        .HasColumnType("float");

                    b.Property<double?>("DiemMieng")
                        .HasColumnType("float");

                    b.Property<double?>("DiemThi")
                        .HasColumnType("float");

                    b.Property<double?>("DiemTrungBinh")
                        .HasColumnType("float");

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<int>("MaHS")
                        .HasColumnType("int");

                    b.Property<int>("MaMon")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDiem");

                    b.HasIndex("MaHS");

                    b.HasIndex("MaMon");

                    b.ToTable("BangDiems");
                });

            modelBuilder.Entity("CNPM.Models.CauLacBo", b =>
                {
                    b.Property<int>("MaCLB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCLB"));

                    b.Property<string>("LichSinhHoat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaGVPhuTrach")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCLB")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ThoiGian")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCLB");

                    b.HasIndex("MaGVPhuTrach");

                    b.ToTable("CauLacBos");
                });

            modelBuilder.Entity("CNPM.Models.GiaoVien", b =>
                {
                    b.Property<int>("MaGV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGV"));

                    b.Property<string>("ChuyenMon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ToChuyenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThaiCongTac")
                        .HasColumnType("bit");

                    b.HasKey("MaGV");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.ToTable("GiaoViens");
                });

            modelBuilder.Entity("CNPM.Models.HinhAnhGioiThieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("UrlAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HinhAnhGioiThieus");
                });

            modelBuilder.Entity("CNPM.Models.HoSoTuyenSinh", b =>
                {
                    b.Property<int>("MaHoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoSo"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DiemAnh")
                        .HasColumnType("float");

                    b.Property<double?>("DiemToan")
                        .HasColumnType("float");

                    b.Property<double?>("DiemVan")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTenPhuHuynh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaLop")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SdtPhuHuynh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TruongCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHoSo");

                    b.HasIndex("MaLop");

                    b.ToTable("HoSoTuyenSinhs");
                });

            modelBuilder.Entity("CNPM.Models.HocSinh", b =>
                {
                    b.Property<int>("MaHS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHS"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTenPhuHuynh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaLop")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SdtPhuHuynh")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThaiHoc")
                        .HasColumnType("bit");

                    b.HasKey("MaHS");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique()
                        .HasFilter("[MaTaiKhoan] IS NOT NULL");

                    b.ToTable("HocSinhs");
                });

            modelBuilder.Entity("CNPM.Models.LopHoc", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<int?>("MaGV")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaGV");

                    b.ToTable("LopHocs");
                });

            modelBuilder.Entity("CNPM.Models.MonHoc", b =>
                {
                    b.Property<int>("MaMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMon"));

                    b.Property<int>("SoTiet")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaMon");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("CNPM.Models.PhanCong", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanCong"));

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<int>("MaGV")
                        .HasColumnType("int");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<int>("MaMon")
                        .HasColumnType("int");

                    b.HasKey("MaPhanCong");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaMon");

                    b.ToTable("PhanCongs");
                });

            modelBuilder.Entity("CNPM.Models.PhongChucNang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HongNang")
                        .HasColumnType("int");

                    b.Property<int>("SuDungTot")
                        .HasColumnType("int");

                    b.Property<int>("SuaChuaNho")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TongSo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhongChucNangs");
                });

            modelBuilder.Entity("CNPM.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LanDangNhapCuoi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaHocSinh")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("TaiKhoans");

                    b.HasData(
                        new
                        {
                            MaTaiKhoan = 1,
                            Email = "admin@thptmuongang.edu.vn",
                            MatKhau = "1",
                            MatKhauHash = "123456",
                            NgayTao = new DateTime(2026, 6, 29, 8, 28, 33, 921, DateTimeKind.Local).AddTicks(2408),
                            Role = "Admin",
                            TenDangNhap = "admin",
                            TrangThai = true,
                            VaiTro = "Admin"
                        });
                });

            modelBuilder.Entity("CNPM.Models.ThamGiaCLB", b =>
                {
                    b.Property<int>("MaHS")
                        .HasColumnType("int");

                    b.Property<int>("MaCLB")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHS", "MaCLB");

                    b.HasIndex("MaCLB");

                    b.ToTable("ThamGiaCLBs");
                });

            modelBuilder.Entity("CNPM.Models.ThongKeNhanSu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DaiHoc")
                        .HasColumnType("int");

                    b.Property<int>("DangBoiDuong")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SauDaiHoc")
                        .HasColumnType("int");

                    b.Property<int>("TongSo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ThongKeNhanSus");
                });

            modelBuilder.Entity("CNPM.Models.ThongTinNhaTruong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HieuTruong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiHinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTruong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoHinhDaoTao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDoKiemDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamThanhLap")
                        .HasColumnType("int");

                    b.Property<int>("PhongHocChuan")
                        .HasColumnType("int");

                    b.Property<int>("PhongHocLon")
                        .HasColumnType("int");

                    b.Property<int>("PhongHocNho")
                        .HasColumnType("int");

                    b.Property<string>("QuyMoCsvc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuyenSuDungDat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuyetDinhThanhLap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TongDienTich")
                        .HasColumnType("float");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThongTinNhaTruongs");
                });

            modelBuilder.Entity("CNPM.Models.TinTuc", b =>
                {
                    b.Property<int>("MaTinTuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinTuc"));

                    b.Property<string>("HinhAnhURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaNguoiDang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaTinTuc");

                    b.HasIndex("MaNguoiDang");

                    b.ToTable("TinTucs");
                });

            modelBuilder.Entity("CNPM.Models.BangDiem", b =>
                {
                    b.HasOne("CNPM.Models.HocSinh", "HocSinh")
                        .WithMany("BangDiems")
                        .HasForeignKey("MaHS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CNPM.Models.MonHoc", "MonHoc")
                        .WithMany("BangDiems")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("CNPM.Models.CauLacBo", b =>
                {
                    b.HasOne("CNPM.Models.GiaoVien", "GiaoVienPhuTrach")
                        .WithMany("CauLacBos")
                        .HasForeignKey("MaGVPhuTrach");

                    b.Navigation("GiaoVienPhuTrach");
                });

            modelBuilder.Entity("CNPM.Models.GiaoVien", b =>
                {
                    b.HasOne("CNPM.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("GiaoVien")
                        .HasForeignKey("CNPM.Models.GiaoVien", "MaTaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("CNPM.Models.HoSoTuyenSinh", b =>
                {
                    b.HasOne("CNPM.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("MaLop");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("CNPM.Models.HocSinh", b =>
                {
                    b.HasOne("CNPM.Models.LopHoc", "LopHoc")
                        .WithMany("HocSinhs")
                        .HasForeignKey("MaLop");

                    b.HasOne("CNPM.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("HocSinh")
                        .HasForeignKey("CNPM.Models.HocSinh", "MaTaiKhoan");

                    b.Navigation("LopHoc");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("CNPM.Models.LopHoc", b =>
                {
                    b.HasOne("CNPM.Models.GiaoVien", "GiaoVien")
                        .WithMany("LopHocChuNhiems")
                        .HasForeignKey("MaGV");

                    b.Navigation("GiaoVien");
                });

            modelBuilder.Entity("CNPM.Models.PhanCong", b =>
                {
                    b.HasOne("CNPM.Models.GiaoVien", "GiaoVien")
                        .WithMany("PhanCongs")
                        .HasForeignKey("MaGV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CNPM.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CNPM.Models.MonHoc", "MonHoc")
                        .WithMany("PhanCongs")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("LopHoc");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("CNPM.Models.ThamGiaCLB", b =>
                {
                    b.HasOne("CNPM.Models.CauLacBo", "CauLacBo")
                        .WithMany("ThamGiaCLBs")
                        .HasForeignKey("MaCLB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CNPM.Models.HocSinh", "HocSinh")
                        .WithMany("ThamGiaCLBs")
                        .HasForeignKey("MaHS")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CauLacBo");

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("CNPM.Models.TinTuc", b =>
                {
                    b.HasOne("CNPM.Models.TaiKhoan", "TaiKhoanNguoiDang")
                        .WithMany("TinTucs")
                        .HasForeignKey("MaNguoiDang");

                    b.Navigation("TaiKhoanNguoiDang");
                });

            modelBuilder.Entity("CNPM.Models.CauLacBo", b =>
                {
                    b.Navigation("ThamGiaCLBs");
                });

            modelBuilder.Entity("CNPM.Models.GiaoVien", b =>
                {
                    b.Navigation("CauLacBos");

                    b.Navigation("LopHocChuNhiems");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("CNPM.Models.HocSinh", b =>
                {
                    b.Navigation("BangDiems");

                    b.Navigation("ThamGiaCLBs");
                });

            modelBuilder.Entity("CNPM.Models.LopHoc", b =>
                {
                    b.Navigation("HocSinhs");
                });

            modelBuilder.Entity("CNPM.Models.MonHoc", b =>
                {
                    b.Navigation("BangDiems");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("CNPM.Models.TaiKhoan", b =>
                {
                    b.Navigation("GiaoVien")
                        .IsRequired();

                    b.Navigation("HocSinh")
                        .IsRequired();

                    b.Navigation("TinTucs");
                });
#pragma warning restore 612, 618
        }
    }
}
